dist: xenial
language: python
python:
  - &latest_py2 2.7
  - 3.5
  - 3.6
  - &latest_py3 3.7

jobs:
  fast_finish: true
  include:
  - python: *latest_py3
    env: LANG=C
  - python: *latest_py2
    env: LANG=C
  - stage: deploy (to PyPI for tagged commits)
    if: tag IS present
    python: *latest_py3
    install: skip
    script: skip
    after_success: true
    before_deploy:
    - python setup.py sdist bdist_wheel
    deploy:
      provider: pypi
      user: voxpupuliorg
      distributions: sdist bdist_wheel
      skip_cleanup: true
      skip_upload_docs: true
      password:
        secure: "tw/8BDuEPPpqTm/LXhWe6OpLVvKJ7/3hNRIiiloYakaBIpT76RmMlgI+urq6+UTrVopDW++ZnZnNhO/84KNJD0yhWIMAdeapa2kQwyAEH6grKryd/do2kfRB04huxiCZ/61T8/zW9pUObqM5MWW8E68H9fa14YiOP4zkLLrlxkA="
      on:
        tags: true
        all_branches: true

cache: pip

install:
  - pip install -r requirements-test.txt
script:
  - py.test --cov=pypuppetdb --pep8  -v
  - bandit -r pypuppetdb
  - bandit -r tests -s B101
after_success:
  - coveralls
notifications:
  email: false
  irc:
    on_success: always
    on_failure: always
    channels:
      - "chat.freenode.org#voxpupuli-notifications"
