language: python
python:
  - 2.7
  - 3.5
  - 3.6
install:
  - pip install -q -r requirements.txt
  - pip install -q coverage coveralls
script:
  - py.test --cov=pypuppetdb --pep8  -v
  - ./bandit.sh
after_success:
  - coveralls
notifications:
  email: false
